name: mini-sedric

services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: dev
    command: "poetry run fastapi dev main.py --host 0.0.0.0"
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4567:4566"
    environment:
      - SERVICES=s3:4566
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
      - DEFAULT_REGION=eu-central-1
    volumes:
      - "../init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - "../aws:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
