[development]
aws_access_key_id = "foobar"
aws_secret_access_key = "test"
region_name = "eu-central-1"
s3_aws_endpoint = "http://localstack:4566"
transcribe_aws_endpoint = "http://localstack:4566"
s3_bucket_name = "test-bucket"

[testing]
aws_access_key_id = "test"
aws_secret_access_key = "test"
region_name = "eu-central-1"
s3_aws_endpoint = "http://localstack:4566"
transcribe_aws_endpoint = "http://localstack:4566"
s3_bucket_name = "test-bucket"
