[development]
aws_access_key_id = "foobar"
aws_secret_access_key = "test"
region_name = "eu-central-1"
aws_endpoint = "http://localstack:4566"

[testing]
aws_access_key_id = "test"
aws_secret_access_key = "test"
region_name = "eu-central-1"
