# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ci:
    strategy:
     fail-fast: false
     matrix:
       python-version: ["3.11"]
       poetry-version: ["1.8.3"]
       os: [ubuntu-latest]
    runs-on:
      ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install projects dependencies
        run: poetry install
      - name: Linters & Formatters
        run: poetry run check
      - name: Tests
        run: ENV_FOR_DYNACONF=testing poetry run pytest
